version: '3.0'
services: 
  nexus:
    container_name: nexus
    image: sonatype/nexus3
    expose:
      - 8081
      - 5000
      - 15000
      - 15001
    volumes: 
      - /var/lib/nexus3:/nexus-data
    networks:
      - nexus-net
  nexus-httpd-proxy:
    container_name: nexus-httpd-proxy
    image: bi/nexus-httpd-proxy
    volumes: 
      - /var/lib/nexus3-httpd-proxy/ssl:/etc/httpd/ssl
      - ./nexus-proxy.conf:/etc/httpd/conf/httpd.conf
    ports:
      - 80:80
      - 443:443
      - 5000:5000
    networks:
      - nexus-net

networks:
  nexus-net:
